### PR TITLE
Fix creating urls from invalid strings

### LINKED ISSUE #47: Spatie menu fails of Url::fromString method fails
Spatie menu has a method `ActiveUrlChecker::check` (https://github.com/spatie/menu/blob/master/src/ActiveUrlChecker.php#L10) that calls `Url::fromString`.

Because url path can be invalid (our case `///remote/fgt_lang?lang=/../../../..//////////dev/`) it will throw an exception:
1. `parse_url('///remote/fgt_lang?lang=/../../../..//////////dev/')` will return `false`
2. `array_merge(false)` finally throw an exception https://github.com/spatie/url/blob/master/src/Url.php#L43

Why it needed to do `array_merge` with only 1 argument?
What to do if `parse_url` failed?

### PR DESCRIPTION
**Pull request by SamuelNitsche**
This PR fixes #47

### CODE REVIEW

File: src/Url.php [hunk 1]
```diff
@@ -40,7 +40,9 @@ public static function create(): static
 
     public static function fromString(string $url): static
     {
-        $parts = array_merge(parse_url($url));
```
Comment (SamuelNitsche) [inline src/Url.php:43]: I removed the whole `array_merge` part since this isn't really needed

File: src/Url.php [hunk 2]
```diff
@@ -40,7 +40,9 @@ public static function create(): static
...
+        if (! $parts = parse_url($url)) {
+            throw InvalidArgument::invalidUrl($url);
+        }
```
Comment (SamuelNitsche) [inline src/Url.php:45]: Maybe this could be extracted to another method

**Comment by freekmurze** [comment]
Thanks!
